version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: booksdb
    ports:
      - "3307:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
