apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  type: NodePort
  selector:
    app: bookstore
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
