apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-app
  labels:
    app: bookstore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
        - name: bookstore-app
          image: yerkazy/bookstore-app:1.0.1
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-port
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: admin
            - name: DB_NAME
              value: booksdb
