apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6
  template:
    metadata:
      labels:
        app: k6
    spec:
      containers:
        - name: k6
          image: grafana/k6:latest
          args: ["run", "/scripts/load-test.js"]
          volumeMounts:
            - name: k6-script-volume
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: k6-script-volume
          configMap:
            name: k6-script
